spring:
  thymeleaf:
    content-type: text/html
    enabled: true
    mode: HTML5
    suffix: .html
    cache: false

  social:
    twitter:
      app-id: XHYkM7qaRCEpgAcS7OesQfSuC
      app-secret: WiWkeFOCbhPkCqvGEMVdY01yMTZ12tZys3RuJQYmOGSkuUPSeE
