language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: B8c3qW9LC01YqsRAMtHc3S5fnhFxcTiRqoKIoLZJcFQi+nci21d7QIv9eMyUxupKDokfXjqW2yc1JNN7VU25U/rU8vbfIEEoH6TqWOGiwSL+dF718GM5UHdnM/2cbefo9WU/bBQzfNV+fR881y5auasAZns87oFNQ4PIyQ2xpwQ=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/org.dawnsci.marketplace.server/target/org.dawnsci.marketplace.server-*.war
  on:
    repo: itema-as/eclipse-marketplace-server
    tags: true
    all_branches: true